project_id = "fyxnuhqzgkzfuldqurej"

[functions.delete-user]
verify_jwt = true

[functions.update-user-email]
verify_jwt = true

[functions.update-user-password]
verify_jwt = true

[functions.test-todo-reminders]
verify_jwt = false

[functions.auto-todo-reminders]
verify_jwt = false

[functions.generate-admission-case]
verify_jwt = false

[functions.extract-milestones]
verify_jwt = false

[functions.parse-document]
verify_jwt = false
